language: node_js
cache:
  directories:
    - '~/.npm'
node_js:
  - '10'
install:
  - npm ci
script:
  - echo "Hello World"
after_success:
  - curl -H "Authorization: Bearer ${GITHUB_TOKEN}" -X POST -d "{\"body\": \"Hello world\"}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"